[unix_http_server]
file=/tmp/supervisor.sock
chmod=0700

[supervisord]
nodaemon=true
logfile=/tmp/supervisord.log
pidfile=/tmp/supervisord.pid
childlogdir=/tmp

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///tmp/supervisor.sock


[program:redis]
command=redis-server --requirepass Intelly
autostart=true
autorestart=true

[program:celery_worker]
# command=/opt/venv/bin/celery -A celery_report_gen worker -l info -Q dev_report_task_queue --pool threads --concurrency 1
command=/opt/venv/bin/celery -A celery_report_gen worker -l info -Q prod_report_task_queue --pool threads --concurrency 1
directory=/app
autostart=true
autorestart=true

[program:kafka_listener]
command=/opt/venv/bin/python kafka_listener.py
directory=/app
autostart=true
autorestart=true

# [supervisorctl]
# serverurl=unix:///tmp/supervisor.sock